name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: .NET + Angular SonarQube Analysis
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup Java 17 (required by SonarQube)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: pwsh

      - name: Begin SonarQube analysis
        run: |
          dotnet-sonarscanner begin `
            /k:"DevSecOpsApp" `
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh

      - name: Restore & Build .NET backend
        run: |
          dotnet restore DevSecOpsApp.sln
          dotnet build DevSecOpsApp.sln --no-incremental --configuration Release
        shell: pwsh

      - name: End SonarQube analysis
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh

      - name: Install Angular dependencies
        working-directory: ./src
        run: npm ci

      - name: Run Angular build
        working-directory: ./src
        run: npm run build
